### ISSUE TITLE
ERROR: Failed to timestamp all previous hashes

### ISSUE THREAD

**Issue by stevenjwright** [ipguard/ipguard#1]
Hey, I was trying to get this set up on an existing project (running on MacOS 10.15.4).

I ran the curl command and received the following:

``` \u2022 Declare your Git respository
  Your repository is named slipstream
  The asset was declared to IPGuard as slipstream
  \u2713 Done

\u2022 Timestamp all past commits
sed: 1: "all_commit_hashs.txt": command a expects \ followed by text
  Timestamp 167 commits
  ERROR: Failed to timestamp all previous hashes
  Please report this issue to https://github.com/ipguard/ipguard/issues
```

As per it says, I am reporting this to you 👍

Also, fyi, noticed a slight typo ` \u2022 Declare your Git respository` -> Repository spelt wrong. 

Cheers!

Sidenote, great idea for a project this. Nice work 👏

**Comment by phbernard** [comment]
Thank you for reporting this issue! 👍 

Hum... troubles with `sed`, which might be specific to macOS (it works fine on Linux and Cygwin), and I don't have a Mac at hand. I need to rent one in the cloud just the time to debug. Will do this either today or on Sunday.

At least the typo is fixed :)

**Comment by phbernard** [comment]
Fixed at last. The issue was due to a difference in `sed` behavior between Linux and macOS. For some reasons, macOS's `sed` is not happy with in-place file jobs. The workaround is to use `sed` in pipe mode instead.

Oh, and unicode characters were fixed to be displayed nicely by macOS terminal.

I would be glad if you could give it another shot and confirm it works for you too.

**Comment by stevenjwright** [comment]
@phbernard apologies, somehow missed your comment... just tested now and works like a treat, thanks! 🙏
